Form close detection
df-mc/dragonfly pull request #248
Opened 2021-08-19 13:39 UTC by Endermanbugzjfc

Code has shitty doc please fix doc

2021-08-19 13:58 UTC, Lucaskyy requested changes

2021-08-19 13:58 UTC, Lucaskyy commented on server/player/form/submit.go
> +// Closer represents a form which has special logic when being closed by a Submitter. The struct struct will have its Close method called, when its form is closed.
`struct struct` -> `form`
`its form` -> `it is`

2021-08-19 14:38 UTC, Lucaskyy commented
Isn't `Closable` a better name than `Closer`?

2021-08-20 08:43 UTC, Sandertv reviewed
Just some documentation nitpicks, looks good otherwise.

2021-08-20 08:43 UTC, Sandertv commented on server/player/form/submit.go
> +// Closer represents a form which has special logic when being closed by a Submitter. The form will have its Close method called, when it is closed.
Would remove the `The form...is closed' sentence as the Close method documents that.

2021-08-20 08:43 UTC, Sandertv commented on server/player/form/submit.go
> +type Closer interface {
Please add a `.` at the end.

2021-08-20 08:55 UTC, Lucaskyy approved these changes

2021-08-20 08:56 UTC, Sandertv approved these changes
Looks good, thank you!

2021-08-20 08:56 UTC, merged