Added Held Slot handler
df-mc/dragonfly pull request #430
Opened 2022-02-20 07:01 UTC by CiviledCode

- Removed session.UpdateHeldSlot
- Added player.SetHeldSlot
- Added HeldSlotChange to handler

2022-02-20 07:03 UTC, JustTalDevelops commented on server/player/handler.go
> +
Would remove these empty gaps and the empty comment to match the format.

2022-03-28 22:19 UTC, T14Raptor requested changes

2022-03-28 22:19 UTC, T14Raptor commented on server/player/player.go
> +	if slot > 8 {
Why'd you remove all the documentation for this method?

2022-03-28 22:19 UTC, T14Raptor commented on server/player/player.go
> +		return fmt.Errorf("client side item isn't equal to expected slot item")
This code no longer belongs here now that it's a player method, should be moved to packet handling (check a0bb8dde26bc089aac89d2625cb45a8a1dfe6523).

2022-03-28 22:19 UTC, T14Raptor commented on server/player/player.go
> +	p.ReleaseItem()
Should just set `(Player).usingItem` to false here.

2022-03-28 22:19 UTC, T14Raptor commented on server/player/player.go
> +func (p *Player) SetHeldSlot(slot int, expected item.Stack) error {
Passing an expected item stack no longer makes sense here, should be removed.

2022-03-28 22:19 UTC, T14Raptor commented on server/player/player.go
> +// SetHeldSlot updates the held slot of the player with the slot passed. It also verifies that the item within the spot
Should remove the middle sentence in this doc.

2022-07-14 06:13 UTC, JustTalDevelops commented
Any update on this?

2022-07-20 18:05 UTC, closed without merging