Mending enchantment
df-mc/dragonfly pull request #552
Opened 2022-07-11 05:32 UTC by Prim69

2022-07-11 14:33 UTC, JustTalDevelops commented on server/item/enchantment/mending.go
> +type Mending struct{}
Make sure to implement the Rarity function, introduced with anvils.

2022-07-11 14:34 UTC, JustTalDevelops commented on server/item/enchantment/mending.go
> +type Mending struct{}
Along with the `CompatibleWithEnchantment` function, and the rename from `CompatibleWith` to `CompatibleWithItem`.

2022-07-15 08:10 UTC, Sandertv requested changes
I've left a couple of comments. Functionally the code looks fine to me, so it shouldn't be too much more work.

2022-07-15 08:10 UTC, Sandertv commented on server/item/enchantment/mending.go
> +	//_, infinity := t.(Infinity) todo: infinity
Could you uppercase this `TODO` for consistency? 😄

2022-07-15 08:10 UTC, Sandertv commented on server/player/player.go
> +	if length := len(mendingItems); length > 0 {
I'd invert this check and return if length = 0 (after moving this into its separate function.

2022-07-15 08:10 UTC, Sandertv commented on server/player/player.go
> +	}
I think it'd be a good idea to move this entire block into its own function. We'd want that to return the amount of leftover XP so we can use that for the rest of the code after it in this function.

2022-07-16 13:43 UTC, Sandertv reviewed
Just one last comment, feel free to ping me on Discord once you've resolved it. Should be good to merge after it.

2022-07-16 13:43 UTC, Sandertv commented on server/player/player.go
> +func (p *Player) handleMending(value int) int {
Would probably name this method `mendItems(xp int)` to be a bit more descriptive.

2022-07-16 20:39 UTC, JustTalDevelops approved these changes

2022-07-16 20:40 UTC, merged