Implement blackstone and deepslate blocks and walls
df-mc/dragonfly pull request #611
Opened 2022-07-30 23:12 UTC by TwistedAsylumMC

2022-07-31 01:52 UTC, DaPigGuy requested changes

2022-07-31 01:52 UTC, DaPigGuy commented on server/block/blackstone.go
> +	return newBreakInfo(hardness, pickaxeHarvestable, pickaxeEffective, drops).withBlastResistance(30)
```suggestion
	drops := oneOf(b)
	if b.Type == GildedBlackstone() {
		drops = func(item.Tool, []item.Enchantment) []item.Stack {
			if rand.Float64() < 0.1 {
				return []item.Stack{item.NewStack(item.GoldNugget{}, rand.Intn(4)+2)}
			}
			return []item.Stack{item.NewStack(b, 1)}
		}
	}
	return newBreakInfo(1.5, pickaxeHarvestable, pickaxeEffective, drops).withBlastResistance(30)
```

2022-07-31 01:52 UTC, DaPigGuy commented on server/block/deepslate.go
> +
Missing smelt info for cobbled deepslate

2022-07-31 01:52 UTC, DaPigGuy commented on server/block/deepslate_bricks.go
> +
Missing smelt info

2022-07-31 01:52 UTC, DaPigGuy commented on server/block/deepslate_tiles.go
> +
Missing smelt info

2022-07-31 01:52 UTC, DaPigGuy commented on server/block/polished_blackstone_brick.go
> +type PolishedBlackstoneBrick struct {
Missing doc

2022-08-01 03:55 UTC, JustTalDevelops approved these changes

2022-08-01 22:03 UTC, Sandertv commented
I imagine it's easiest if we merge these after slabs and stairs and add those in this PR.

2022-08-01 23:39 UTC, Sandertv reviewed
One typo, should be good otherwise when stairs/slabs are added. Feel free to merge once that's resolved.

2022-08-01 23:39 UTC, Sandertv commented on server/block/blackstone.go
> +// furnances. Gilded blackstone also has a 10% chance to drop 2-6 golden nuggets.
Typo here, `furnances`.

2022-08-01 23:53 UTC, merged