Separate network IDs from save IDs
df-mc/dragonfly pull request #634
Opened 2022-08-09 10:02 UTC by Xd-pro

Allows multiple entity types to have the same network ID.

2022-08-09 21:19 UTC, DaPigGuy commented on server/world/entity.go
> +type NetworkedEntity interface {
Missing a doc here

2022-08-10 05:30 UTC, DaPigGuy commented on server/world/entity.go
> +	// Returns the network type ID of the entity. This is NOT the save ID.
This doc should begin with `// NetworkTypeID`

2022-08-10 20:39 UTC, DaPigGuy commented on server/world/entity.go
> +// NetworkEncodeableEntity is an Entity where the save ID and network ID is not the same.
```suggestion
// NetworkEncodeableEntity is an Entity where the save ID and network ID are not the same.
```

2022-08-14 11:56 UTC, Sandertv requested changes
I've left a couple of comments. I think this is ready to go once those and the ones left by @DaPigGuy are resolved.

2022-08-14 11:56 UTC, Sandertv commented on server/world/entity.go
> +	Entity
No reason to have this embed `Entity`.

2022-08-14 11:56 UTC, Sandertv commented on server/entity/text.go
> +func (*Text) NetworkTypeID() string {
This method should be called `NetworkEncodeEntity`.

2022-08-14 11:56 UTC, Sandertv commented on server/world/entity.go
> +type NetworkEncodeableEntity interface {
I'd consider moving this to the session package, as that's the only place where the interface is used.

2022-08-14 20:47 UTC, DaPigGuy commented on server/world/entity.go
> +
Please revert all changes to this file

2022-08-15 18:38 UTC, DaPigGuy commented on server/entity/text.go
> +func (*Text) NetworkTypeID() string {
```suggestion
func (*Text) NetworkEncodeEntity() string {
```

2022-08-19 10:23 UTC, Sandertv approved these changes
This looks good. Thank you for the PR!

2022-08-19 10:24 UTC, merged