Implemented lecterns
df-mc/dragonfly pull request #651
Opened 2022-08-20 20:21 UTC by JustTalDevelops

2022-08-20 20:41 UTC, DaPigGuy approved these changes

2022-10-23 12:26 UTC, Sandertv requested changes
Looks fine mostly. I'm only not sure about the NBT "tag" changes. What are those based on?

2022-10-23 12:26 UTC, Sandertv commented on server/block/lectern.go
> +	return true
You should probably return false if item is not a book or if the Lectern already held a book (first check).

2022-10-23 12:26 UTC, Sandertv commented on server/block/lectern.go
> +		// We're already on the correct page, so ignore this packet.
Wouldn't say "ignore this packet" here because there's no packet at this stage.

2022-10-23 12:26 UTC, Sandertv commented on server/block/model/lectern.go
> +	return []cube.BBox{full.ExtendTowards(cube.FaceDown, 0.1)}
This isn't very clear. I would use the `cube.Box()` function instead.

2022-10-23 12:26 UTC, Sandertv commented on server/player/player.go
> +func (p *Player) CanReach(pos mgl64.Vec3) bool {
I'm hesitant on making this an exported function. I think it'd be better to keep this unexported and do this check in the EditSign method so we can keep this as it was.

2022-10-23 12:26 UTC, Sandertv commented on server/session/controllable.go
> +	CanReach(pos mgl64.Vec3) bool
As mentioned above, would undo this.

2022-10-23 12:26 UTC, Sandertv commented on server/session/handler_lectern_update.go
> +	return lectern.TurnPage(pos, w, int(pk.Page))
Would perform this code in some `(*Player).EditLectern()` method (or a better method if you feel like it, maybe something that's more clear about the fact it's only turning pages).

2022-10-23 12:26 UTC, Sandertv commented on server/internal/nbtconv/mapread.go
> +		t := Map[map[string]any](m, "tag")
Is this correct for every item in Bedrock Edition? I feel it's weird we didn't have this before, so we need to make sure this matches Bedrock Edition.

2022-10-23 15:38 UTC, JustTalDevelops commented
The NBT changes are based on vanilla Minecraft. Everything that does not define the item type goes inside the tag field.

2022-12-16 19:38 UTC, JustTalDevelops commented
This should be ready for review now.

2022-12-16 20:56 UTC, DaPigGuy approved these changes

2022-12-16 20:56 UTC, DaPigGuy commented on server/player/player.go
> +// present or if the Player cannot edit it, an error is returned.
> or if the Player cannot edit it, an error is returned.

doesn't seem to be the case

2023-07-04 21:01 UTC, merged