Patch food
df-mc/dragonfly pull request #677
Opened 2022-10-05 14:29 UTC by Blackjack200

# Tests
```patch
diff --git a/main.go b/main.go
index b1905144..35072aed 100644
--- a/main.go
+++ b/main.go
@@ -3,8 +3,6 @@ package main
 import (
 	"fmt"
 	"github.com/df-mc/dragonfly/server"
-	"github.com/df-mc/dragonfly/server/event"
-	"github.com/df-mc/dragonfly/server/player"
 	"github.com/df-mc/dragonfly/server/player/chat"
 	"github.com/pelletier/go-toml"
 	"github.com/sirupsen/logrus"
@@ -12,11 +10,6 @@ import (
 )
 
 func main() {
-	aa := a{}
-	to := 1
-	logrus.Infof("1 main: to:%v", to)
-	aa.HandleFoodLoss(event.C(), 20, &to)
-	logrus.Infof("2 main: to:%v", to)
 	log := logrus.New()
 	log.Formatter = &logrus.TextFormatter{ForceColors: true}
 	log.Level = logrus.DebugLevel
@@ -36,16 +29,6 @@ func main() {
 	}
 }
 
-type a struct {
-	player.NopHandler
-}
-
-func (a) HandleFoodLoss(_ *event.Context, from int, to *int) {
-	logrus.Infof("1 HandleFoodLoss: from:%v to:%v", from, *to)
-	*to = 0
-	logrus.Infof("2 HandleFoodLoss: from:%v to:%v", from, *to)
-}
-
 // readConfig reads the configuration from the config.toml file, or creates the
 // file if it does not yet exist.
 func readConfig(log server.Logger) (server.Config, error) {

```

## Excepted Result
```
INFO[0000] 1 main: to:1
INFO[0000] 1 HandleFoodLoss: from:20 to:1
INFO[0000] 2 HandleFoodLoss: from:20 to:0
INFO[0000] 2 main: to:0
```

## Actual Result
```
INFO[0000] 1 main: to:1
INFO[0000] 1 HandleFoodLoss: from:20 to:1
INFO[0000] 2 HandleFoodLoss: from:20 to:0
INFO[0000] 2 main: to:0
```

2022-11-16 10:47 UTC, Flonja requested changes
Just some small changes

2022-11-16 10:47 UTC, Flonja commented on server/player/handler.go
> -func (NopHandler) HandlePunchAir(*event.Context)                                              {}
This seems like a change that didn't need to get made

2022-11-16 10:47 UTC, Flonja commented on server/player/handler.go
> +func (NopHandler) HandleDeath(world.DamageSource, *bool)                                                 {}
Just like this extra whitespace

2022-12-16 16:26 UTC, Sandertv reviewed
The build doesn't currently pass because of the reasons stated above by @Flonja. This should be ready to go once the build issues are fixed.

2022-12-16 17:24 UTC, merged