Added function to compare chunks
df-mc/dragonfly pull request #841
Opened 2024-01-10 13:44 UTC by ethaniccc

This allows for two chunks with two different pointers to still be compared for equality. 
(pls merge so I don't have to update oomph's fork 🙏)

2024-01-10 15:09 UTC, Sandertv reviewed
Feel free to combine some of these checks into a single statement. That shouldn't lead to a longer execution time.

2024-01-12 23:28 UTC, ethaniccc commented
👍

2024-02-11 21:04 UTC, ethaniccc commented
bump

2024-02-12 22:22 UTC, RestartFU commented
> bump

rebump

2024-02-13 21:44 UTC, cqdetdev commented
bumpy

2024-02-14 14:49 UTC, RestartFU commented
can we merge this? I'd like to be able to get rid of my dragonfly fork I'm currently using

2024-02-17 02:54 UTC, RestartFU requested changes
can you run `go fmt` :)

2024-02-19 12:43 UTC, didntpot commented
@ethaniccc :V

2024-03-04 05:32 UTC, RestartFU requested changes

2024-03-04 05:32 UTC, RestartFU commented on server/world/chunk/sub_chunk.go
> +	if s.air != sub.air || !slices.Equal(s.blockLight, sub.blockLight) ||
```suggestion
	if s.air != sub.air ||
```

2024-03-04 05:32 UTC, RestartFU commented on server/world/chunk/sub_chunk.go
> +		!slices.Equal(s.skyLight, sub.skyLight) || len(s.storages) != len(sub.storages) {
```suggestion
		len(s.storages) != len(sub.storages) {
```

2024-03-15 21:50 UTC, closed without merging