TrampleCrop Handler
df-mc/dragonfly pull request #868
Opened 2024-05-02 01:44 UTC by xNatsuri

This PR implements TrampleCrop handler to prevent players from trampling crops.

2024-05-26 12:25 UTC, Sandertv requested changes
I think it might be more suitable to have a HandleCropTrample method in `world.Handler`. That way we don't have to duplicate this method for every entity (because ultimately, all entities can trample crops). That would mean calling this event in the EntityLand method of `block.Farmland`.

2024-05-26 16:09 UTC, xNatsuri commented
I was looking through issues when I saw this and I saw the discussion that you and Tal both thought it would be better to have it in a player/entity handler

2024-05-26 16:36 UTC, Sandertv commented
Good point, let me think about it a bit more.

2024-08-25 17:30 UTC, Sandertv reviewed
I think it's fine to have this as a player handler. Got one more comment naming wise, but otherwise all is good once conflicts are resolved.

2024-08-25 17:30 UTC, Sandertv commented on server/player/handler.go
> +	HandleTrampleCrop(ctx *event.Context)
Would maybe rename this to HandleCropTrample to be more in line with the other method names.

2024-08-25 18:18 UTC, xNatsuri commented
should be good to merge

2024-08-25 19:10 UTC, xNatsuri commented
added position of crop users might find it useful if they just want to cancel it in a certain area

2024-08-31 16:27 UTC, Sandertv approved these changes
Looks good! Thanks for the PR!

2024-08-31 16:27 UTC, merged