Feature/reset food saturation
df-mc/dragonfly pull request #903
Opened 2024-07-22 23:45 UTC by aabstractt

Add reset the exhaustion and saturation when the Food Loss handler is cancelled. This help to prevent loss very fast the food after no longer cancelling that handler.

Example

https://github.com/user-attachments/assets/ab8d9917-2c1e-4568-9b98-7da8e6bbb1d2

2024-07-24 05:56 UTC, didntpot requested changes
the logic here is wrong

2024-07-24 06:17 UTC, didntpot commented
race condition plz add mutex

2024-07-24 06:19 UTC, CJMustard1452 requested changes
fix race conditions

2024-07-24 06:20 UTC, didntpot requested changes

2024-07-24 06:20 UTC, didntpot commented on server/player/hunger.go
> +func (m *hungerManager) resetExhaustion() {
this function cause race condition plz fix

2024-07-24 06:28 UTC, CJMustard1452 requested changes

2024-07-24 06:28 UTC, CJMustard1452 commented on server/player/hunger.go
> +func (m *hungerManager) resetExhaustion() {
```suggestion
func (m *hungerManager) resetExhaustion() {
	m.mu.Lock()
	defer m.mu.Unlock()
```

2024-07-24 06:32 UTC, didntpot requested changes
plz

2024-07-24 06:32 UTC, didntpot commented on server/player/hunger.go
> +// ResetExhaustion resets the exhaustion level of the player to 0.
```suggestion
// ResetExhaustion resets the player's exhaustion level to 0.```

2024-07-24 06:32 UTC, didntpot commented on server/player/hunger.go
> +// Prevents the player food level decrease after non cancelling the food loss
```suggestion
// Prevents the player's food level from decreasing after preventing food loss.
```

2024-07-25 06:18 UTC, CJMustard1452 commented on server/player/hunger.go
> +// Prevents the player food level decrease after non cancelling the food loss
agreed.

2024-07-25 07:09 UTC, CJMustard1452 approved these changes
Looks good.

2024-08-15 09:44 UTC, TwistedAsylumMC commented
Should it reset it to 0 or what it was before the last event was cancelled?

2024-11-27 18:43 UTC, Sandertv approved these changes
I think this is a sensible change. Thank you for the PR!

2024-11-27 18:44 UTC, merged