Add flight speed
df-mc/dragonfly pull request #917
Opened 2024-09-02 13:09 UTC by Sergittos

2024-09-02 16:39 UTC, TwistedAsylumMC requested changes
Thanks for the PR! Aside from the one comment, would you also be willing to extend this to also send the player's speed in the UpdateAbilities packet, assuming that doesn't cause any extra issues just so we can eliminate the TODO completely. If it's not as simple then I'm happy to merge this after the type is changed.

2024-09-02 21:46 UTC, Sergittos commented on server/session/controllable.go
> +	FlightSpeed() float32
Sure

2024-09-02 22:12 UTC, Sergittos commented
> Thanks for the PR! Aside from the one comment, would you also be willing to extend this to also send the player's speed in the UpdateAbilities packet, assuming that doesn't cause any extra issues just so we can eliminate the TODO completely. If it's not as simple then I'm happy to merge this after the type is changed.

Added it, after some tests it seems that the walk speed only modifies the player's fov.

2024-11-17 11:49 UTC, closed without merging

2024-11-17 11:58 UTC, DaPigGuy commented
Sorry, git mishap happened

Merged manually as b4e2e0d7568add07c1d0e9c2f7bd59f24245cea7