Feature/winter drop
df-mc/dragonfly pull request #939
Opened 2024-11-17 21:58 UTC by inotflying

# [Winter Drop](https://minecraft.wiki/w/Winter_Drop)

- [ ] [Creaking Heart](https://minecraft.wiki/w/Creaking_Heart)
  - [ ] Implementation
  - [ ] Documentation
 - [ ] Pale Oak wood type
   - [x] Implementation
   - [ ] Documentation
- [ ] New foliage and vegetation blocks
  - [ ] Implementation
  - [ ] Documentation
- [ ] Resin
  - [x] Implementation
  - [ ] Documentation
- [x] Pale Garden biome

2024-11-17 22:04 UTC, celishere commented
найди работу

2024-11-17 22:15 UTC, TwistedAsylumMC commented
I think it's fine to not implement creaking blocks since we do not have entity support. If you get the chance to do the other foliage/vegation then that would be appreciated!

2024-11-17 23:06 UTC, TwistedAsylumMC requested changes

2024-11-17 23:06 UTC, TwistedAsylumMC commented on server/block/sign.go
> +	}
Can you compare s.Wood to DarkOakWood() instead, i'd also change the statement below to compare to OakWood()

2024-11-22 07:01 UTC, DaPigGuy commented on server/item/resin_clump.go
Resin clump is also a block

2024-12-15 07:08 UTC, DaPigGuy commented
I've cherry-picked 566d32bd3c88599d7080cd28ce9b8de9ba95c26c and 26c6f487c842f0f13de95b6721f0ee1a58e7e58a

2024-12-15 07:34 UTC, DaPigGuy commented
I have cherry-picked and fixed-up the remaining two commits for Resin blocks/items. The Resin Clump item has been dropped for now as it needs additional work for the block.

Thanks for the contributions!

2024-12-15 07:34 UTC, closed without merging